sudo: false

language: groovy

jdk:
- openjdk7

install:
  - export ICE_HOME=${TRAVIS_BUILD_DIR}
  - ./grailsw clean
  - yes | ./grailsw refresh-dependencies

script: 
  - bash -n install.sh
  - ./grailsw compile